amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    global_frame_id: "map"
    odom_frame_id: "odom"
    max_particles: 2000
    min_particles: 500
    pf_err: 0.05
    pf_z: 0.99
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 5.0
      z: 0.0
      yaw: 0.0
    scan_topic: "scan"
    z_hit: 0.95
    z_short: 0.1
    z_max: 0.05
    z_rand: 0.05
   